"""add opening balance to bank accounts

Revision ID: 0e2dfdc4a622
Revises: c92f1a5d7e30
Create Date: 2026-08-14 06:56:20.666396
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e2dfdc4a622'
down_revision: Union[str, None] = 'c92f1a5d7e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('bank_accounts', sa.Column('opening_balance_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'opening_balance_date')
    op.drop_column('bank_accounts', 'opening_balance')
    # ### end Alembic commands ###
