"""initial schema

Revision ID: 27db83110400
Revises: 
Create Date: 2026-08-11 05:45:18.356111
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27db83110400'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tariff_plan', sa.Enum('start', 'pro', 'enterprise', name='tariffplan'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', name='categorytype'), nullable=False),
    sa.Column('parent_category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('forecast_week_start', sa.Date(), nullable=False),
    sa.Column('predicted_cash_in', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('predicted_cash_out', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('predicted_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'accountant', 'viewer', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('category_rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('counterparty_pattern', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'counterparty_pattern', name='uq_company_counterparty')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bank_account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', name='importstatus'), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_import_batch_account_period', 'import_batches', ['bank_account_id', 'period_date'], unique=True, postgresql_where=sa.text("status != 'failed'"))
    op.create_table('transactions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('import_batch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bank_account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('direction', sa.Enum('in_', 'out', name='direction'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='UZS', nullable=False),
    sa.Column('counterparty', sa.String(), nullable=False),
    sa.Column('corr_account_code', sa.String(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('category_source', sa.Enum('rule', 'ai', 'manual', name='categorysource'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('pending_review', 'confirmed', name='reviewstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_company_id'), 'transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_transactions_currency'), 'transactions', ['currency'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_review_status'), 'transactions', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_review_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_currency'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('uq_import_batch_account_period', table_name='import_batches', postgresql_where=sa.text("status != 'failed'"))
    op.drop_table('import_batches')
    op.drop_table('category_rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('forecasts')
    op.drop_table('categories')
    op.drop_table('branches')
    op.drop_table('bank_accounts')
    op.drop_table('companies')
    # ### end Alembic commands ###
