"""add token_version

Revision ID: b861aa48319a
Revises: 27db83110400
Create Date: 2026-08-12 05:59:34.821556
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b861aa48319a'
down_revision: Union[str, None] = '27db83110400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
